---
- name: Set up /etc/hosts
  hosts: all
  tasks:
   - name: Remove old hosts if existing
     lineinfile: dest=/etc/hosts regexp="{{ item }}$" state=absent  owner=root group=root mode=0644
     sudo: yes
     with_items: groups.all
     when: item != ansible_hostname

   - name: Ensure new host exists
     lineinfile: dest=/etc/hosts regexp="^{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}" line='{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ item }}' owner=root group=root mode=0644
     sudo: yes
     with_items: groups.all
     when: item != ansible_hostname
