---
- name: Initial playbook
  hosts: all
  tasks:
    - name: Install nginx
      apt: name=nginx state=present
      sudo: yes

    - name: Validate that nginx is installed
      uri: url=http://localhost method=HEAD
