---
- name: Initial playbook
  hosts: all
  tasks:
    - name: Install nginx on Ubuntu/Debian
      apt:  name=nginx state=present
      sudo: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RedHat/CentOs
      yum:  name=nginx state=present
      sudo: yes
      when: ansible_os_family == "RedHat"

    - name: Validate that nginx is installed
      uri:  url=http://localhost method=HEAD
