---
- name: Initial playbook
  hosts: all
  vars:
    packages_to_install:
      - nginx
      - cowsay
  tasks:
    - name: install ALL THE PACKAGES
      apt:  name={{ item }} state=present
      sudo: yes
      when: ansible_os_family == "Debian"
      with_items: packages_to_install

    - name: install nginx
      yum:  name={{ item }} state=present
      sudo: yes
      when: ansible_os_family == "RedHat"
      with_items: packages_to_install   

    - name: validate that nginx is installed
      uri:  url=http://127.0.0.1

    - name: create static root dir
      file: path=/var/www/workshop state=directory owner=www-data group=www-data recurse=true
      sudo: yes
    
    - name: copy static HTML files to root dir
      copy: src=workshop/resources/index.html dest=/var/www/workshop owner=www-data group=www-data
      sudo: yes
      notify:
        - Reload nginx

    - name: disable default site in Nginx
      file: path=/etc/nginx/sites-enabled/default state=absent
      sudo: yes

    - name: Generate our own nginx site
      template: src=workshop/resources/nginx-site.conf.template dest=/etc/nginx/sites-available/nginx-site.conf owner-www-data group=www-data
      sudo: yes
      notify:
        - Reload nginx

    - name: symlink our nginx site
      file: state=link src=/etc/nginx/sites-available/nginx-site.conf path=/etc/nginx/sites-enabled/nginx-site.conf owner=www-data group=www-data
      sudo: yes
      notify:
        - Reload nginx

  handlers:
    - name: Reload nginx
      service: name=nginx state=reloaded
      sudo: yes


