---
- hosts: web-1
  vars:
    - users: ['david@acme.com', 'moshe@acme.com']
    - roles: ['admin', 'developer']

  tasks:
    - name: print out all users
      command: echo "{{ item }}"
      with_items: users
      when: standard | default(false)

    - name: print out user-role matrix
      command: echo "{{ item[0] }} => {{ item[1] }}"
      with_nested:
        - users
        - roles
      when: nested| default(false)

    - name: copy a bunch of YAML files from local host to the managed host
      copy: src={{ item }} dest=/tmp/
      with_fileglob:
        - files/*.yml
      when: glob | default(false)

    - name: register with loops
      command: echo "{{ item }}"
      with_items:
        - one
        - two
      register: echo
      when: reg | default(false)

