---
- hosts: web-1
  sudo: yes

  roles:
    - common
    - nginx

  tasks:

    - name: include vars
      include_vars: vars.yml

    - name: generate site from template
      template: src=templates/{{ item }}.j2 dest=/etc/nginx/sites-available/{{ item }}
      with_items:
        - static
        - dynamic
      notify:
        - reload nginx

    - name: enable site
      file: path=/etc/nginx/sites-enabled/{{ item }} src=/etc/nginx/sites-available/{{ item }} state=link
      with_items:
        - static
        - dynamic
      notify:
        - reload nginx

    - name: create static root dir
      file: path={{ static_root_dir }} state=directory owner=www-data group=www-data recurse=true

    - name: copy static HTML files to root dir
      copy: src={{ item }} dest=/var/www owner=www-data group=www-data
      with_fileglob:
        - files/*.html
      notify:
        - reload nginx

  handlers:

    - include: roles/nginx/handlers/main.yml


- hosts: web-1
  vars:
    - parent_dir: /opt/bigpanda

  tasks:

    - name: create application parent dir
      file: path={{ parent_dir }} owner=vagrant group=vagrant state=directory
      sudo: yes

    - name: clone application to target dir
      git: repo=git@github.com:bigpandaio/ansible-workshop.git dest={{ parent_dir }}/ansible-workshop accept_hostkey=true
      notify:
        - restart app

    - name: npm install
      npm: path={{ parent_dir }}/ansible-workshop/app production={{ (env | default('dev')) == 'prod' }}

    - name: copy upstart configuration
      copy: src=files/demo.conf dest=/etc/init/
      sudo: yes

    - name: start app
      service: name=demo state=started enabled=true
      sudo: yes

  handlers:

    - name: restart app
      service: name=demo state=restarted
      sudo: yes