---
- hosts: web-1
  sudo: yes
  tasks:

    - name: include vars
      include_vars: vars.yml

    - name: install nginx
      apt: name=nginx state=present
      when: ansible_os_family == "Debian"

    - name: install nginx
      yum: name=nginx state=present
      when: ansible_os_family == "RedHat"

    - name: generate site from template
      template: src=templates/{{ item }}.j2 dest=/etc/nginx/sites-available/{{ item }}
      with_items:
        - static
        - dynamic
      notify:
        - reload nginx

    - name: enable site
      file: path=/etc/nginx/sites-enabled/{{ item }} src=/etc/nginx/sites-available/{{ item }} state=link
      with_items:
        - static
        - dynamic
      notify:
        - reload nginx

    - name: delete default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - reload nginx

    - name: create static root dir
      file: path={{ static_root_dir }} state=directory owner=www-data group=www-data recurse=true

    - name: copy static HTML files to root dir
      copy: src={{ item }} dest=/var/www owner=www-data group=www-data
      with_fileglob:
        - files/*.html
      notify:
        - reload nginx

  handlers:

    - name: reload nginx
      service: name=nginx state=reloaded

- hosts: web-1
  vars:
    - parent_dir: /opt/bigpanda

  tasks:

    - name: install nodejs
      include: nodejs.yml

    - name: install git
      apt: name=git state=present
      sudo: yes

    - name: create application parent dir
      file: path={{ parent_dir }} owner=vagrant group=vagrant state=directory
      sudo: yes

    - name: clone application to target dir
      git: repo=git@github.com:bigpandaio/ansible-workshop.git dest={{ parent_dir }}/ansible-workshop accept_hostkey=true

    - name: npm install
      npm: path={{ parent_dir }}/ansible-workshop/app production={{ (env | default('dev')) == 'prod' }}

    - name: run application
      shell: chdir={{ parent_dir }}/ansible-workshop/app free_form="DEBUG=app ./bin/www > /dev/null 2>&1 &"