---
- name: Install Nginx
  apt:  name=nginx state=present
  sudo: yes

- name: Create static root dir
  file: path=/var/www/workshop state=directory owner=www-data group=www-data
  sudo: yes

- name: Copy static HTML files to root dir
  copy: src=index.html dest=/var/www/workshop owner=www-data group=www-data
  sudo: yes
  notify:
    - Reload nginx
  #ansible 2.0: remote_src

- name: Disable default site in Nginx
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes

- name: Generate our own nginx site
  copy: src=site.conf dest=/etc/nginx/sites-available/site.conf owner=www-data group=www-data
  sudo: yes
  notify:
    - Reload nginx

- name: Symlink our nginx site
  file: state=link src=/etc/nginx/sites-available/site.conf path=/etc/nginx/sites-enabled/site.conf owner=www-data group=www-data
  sudo: yes
  notify:
    - Reload nginx

- meta: flush_handlers

- name: Validate that nginx is installed
  uri:  url=http://127.0.0.1
  #ansible 2.0: body_format json
